# Generated by Django 5.0.1 on 2024-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
